
// This file is automatically generated. Do not edit it directly.
// It exports all the functionality from the Supabase integration modules

// Re-export the base client
export { supabase } from './base-client';

// Re-export auth functionality
export * from './auth';

// Re-export business functionality
export * from './business';

// Re-export appointments functionality
export * from './appointments';

// Re-export services functionality
export * from './services';

// Re-export schedules functionality
export * from './schedules';

// Re-export availability functionality
export * from './availability';
